version: "3.3"

services:
    redis:
        image: "redis:alpine"
        
        ports:
            - 6379:6379
            
        networks:
            - microservices

    client:
        build:
            context: core # ./client
            dockerfile: docker/client/Dockerfile 
        
        networks:
            - microservices

        depends_on:
            - server

        env_file:
            - core/.debug.env

    server:
        build:
            context: core # ./server
            dockerfile: docker/server/Dockerfile 
        
        networks:
            - microservices

        depends_on:
            - redis
            - rq-worker

        env_file:
            - core/.debug.env

    # rq-worker:
    #     build:
    #         context: core # ./worker
    #         dockerfile: docker/worker/Dockerfile 

    #     networks:
    #         - microservices

    #     depends_on:
    #         - redis

    #  OR 👇🏻

    rq-worker:
        image: jaredv/rq-docker:0.0.2
        command: rq worker -u redis://redis:6379 high normal low

        networks:
            - microservices

        depends_on:
            - redis



    rq-dashboard:
        image: jaredv/rq-docker:0.0.2 
        command: rq-dashboard -H redis
        ports:
            - 9999:9999
        
        networks:
            - microservices

        depends_on:
            - redis

networks:
    microservices:
