version: "3.3"

services:
    redis:
        image: "redis:alpine"
        
        ports:
            - 6379:6379
            
        networks:
            - microservices

    client:
        build:
            context: core # ./client
            dockerfile: docker/client/Dockerfile 
        
        networks:
            - microservices

        depends_on:
            - server

        env_file:
            - core/.debug.env

    server:
        build:
            context: core # ./server
            dockerfile: docker/server/Dockerfile 
        
        networks:
            - microservices

        depends_on:
            - redis
            - rq-worker

        env_file:
            - core/.debug.env
            

    consumer:
        build:
            context: core # ./consumer
            dockerfile: docker/consumer/Dockerfile

        networks:
            - microservices

        env_file:
            - core/.debug.env

        volumes:
            - ./core:/service/consumer/

        depends_on:
            - redis
            - rq-worker
            - server


    rq-worker:
        build:
            context: core # ./worker
            dockerfile: docker/worker/Dockerfile

        networks:
            - microservices

        env_file:
            - core/.debug.env

        depends_on:
            - redis


    rq-dashboard:
        image: jaredv/rq-docker:0.0.2 
        command: rq-dashboard --redis-url redis://redis:6379/0
        ports:
            - 9181:9181
        
        networks:
            - microservices

        depends_on:
            - redis

networks:
    microservices:

