version: "3.3"

services:
    redis:
        image: redis
        
        ports:
            - 6333:6333
            
        networks:
            - microservices

    client:
        build: client # ./client
        
        networks:
            - microservices

        volumes:
            - ./protobufs:/service/protobufs

        depends_on:
            - "server"

    server:
        build: server # ./server
        
        networks:
            - microservices

        volumes:
            - ./protobufs:/service/protobufs

        depends_on:
            - "redis"

networks:
    microservices:
