version: "3.3"

services:
    redis:
        image: "redis:alpine"
        
        ports:
            - 6379:6379
            
        networks:
            - microservices

    client:
        build:
            context: core # ./client
            dockerfile: docker/client/Dockerfile 
        
        networks:
            - microservices

        depends_on:
            - server

    server:
        build:
            context: core # ./server
            dockerfile: docker/server/Dockerfile 
        
        networks:
            - microservices

        depends_on:
            - redis

    # worker:
    #     build: worker # ./worker

    #     networks:
    #         - microservices

    #     environment:
    #         - REDIS_HOST=redis
    #         - REDIS_PORT=6379

    #     depends_on:
    #         - server
    #         - redis

    #  OR 👇🏻

    rq-worker:
        image: jaredv/rq-docker:0.0.2
        command: rq worker -u redis://redis:6379 high normal low

        networks:
            - microservices

        depends_on:
            - redis
            - server



    # rq-dashboard:
    #     image: jaredv/rq-docker:0.0.2 
    #     command: rq-dashboard -H rq-server
    #     ports:
    #     - 9181:9181
        
    #     networks:
    #         - microservices

    #     depends_on:
    #         - redis

networks:
    microservices:
